name: Publish package (crates.io)

on:
  workflow_call:
    inputs:
      package-name:
        description: The name of the package
        default: ${{github.event.repository.name}}
        type: string
      environment-name:
        description: The name of the environment
        default: crates
        type: string
      rust-toolchain:
        description: The Rust toolchain
        default: ${{vars.RUST_TOOLCHAIN || 'stable'}}
        type: string
    secrets:
      CARGO_REGISTRY_TOKEN:
        description: An authentication token for crates.io
        required: true

jobs:
  package:
    name: Publish Rust package
    runs-on: ubuntu-latest
    environment:
      name: ${{inputs.environment-name}}
      url: https://crates.io/crates/${{inputs.package-name}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{inputs.rust-toolchain}}
      - name: Publish to crates.io
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_REGISTRY_TOKEN}}
