name: Regenerate parser

on:
  workflow_call:
    inputs:
      node-version:
        description: The NodeJS version
        default: ${{vars.NODE_VERSION || 'latest'}}
        type: string
      update-scanner:
        description: Update the scanner
        default: false
        type: boolean
      commit-message:
        description: The commit message
        default: "build: regenerate parser [dependabot skip]"
        type: string
      commit-author-name:
        description: The commit author's username
        default: dependabot[bot]
        type: string
      commit-author-email:
        description: The commit author's email
        default: 49699333+dependabot[bot]@users.noreply.github.com
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
    outputs:
      package-ecosystem: ${{steps.metadata.outputs.package-ecosystem}}
  regenerate:
    runs-on: ubuntu-latest
    needs: [metadata]
    if: needs.metadata.outputs.package-ecosystem == 'npm_and_yarn'
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{inputs.node-version}}
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}
      - name: Regenerate parser
        run: |-
          npm ci --legacy-peer-deps
          npm x -- tree-sitter generate --no-bindings
      - name: Update scanner
        if: inputs.update-scanner == true
        run: |-
          language=$(jq -r '.name' src/grammar.json)
          parent=$(jq -r '.inherits//empty' src/grammar.json)
          if [[ -z $parent ]]; then
            parent=$(gh api --jq '.[]|select(.property_name == "Inherits")|.value' $PROPS_API)
            if [[ -z $parent ]]; then
              parent=$(sed -rn 's/.*require\(.tree-sitter-(\w+)\/grammar.\).*/\1/p' grammar.js)
              if [[ -z $parent ]]; then
                printf '::error::Failed to detect the parent language.\n'; exit 1
              fi
            fi
          fi
          sed "s/tree_sitter_${parent}_/tree_sitter_${language}_/" \
              "node_modules/tree-sitter-${parent}/src/scanner.c" > src/scanner.c
        env:
          GH_TOKEN: ${{github.token}}
          PROPS_API: repos/${{github.repository}}/properties/values
      - name: Commit changes
        run: |-
          if ! git diff --quiet -- src && git add src; then
            git commit -m '${{inputs.commit-message}}'
            git push origin HEAD:$GITHUB_HEAD_REF
          fi
        env:
          GIT_AUTHOR_NAME: ${{inputs.commit-author-name}}
          GIT_AUTHOR_EMAIL: ${{inputs.commit-author-email}}
          GIT_COMMITTER_NAME: ${{inputs.commit-author-name}}
          GIT_COMMITTER_EMAIL: ${{inputs.commit-author-email}}
